services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGODB_DATABASE_URL=mongodb://mongodb:27017/myfindb
      - MONGODB_DATABASE=myfindb
    depends_on:
      - mongodb
    restart: always

volumes:
  mongodb_data: